### ISSUE TITLE
Improper formatting in shopping list

### ISSUE THREAD

**Issue by abhaikollara** [abhaikollara/first-github-contributions#7]
A few items are in all lower case. Can someone fix that ?

**Comment by Aparna106** [comment]
Sent a Pull request for fixes.

**Comment by abhaikollara** [comment]
Cannot find it in my PRs. Could you share the PR link here after you make it ? Thanks

**Comment by Aparna106** [comment]
I believe its this one? https://github.com/Misty106/first-github-contributions/blob/patch-2/shoppinglist

**Comment by abhaikollara** [comment]
> I believe its this one? https://github.com/Misty106/first-github-contributions/blob/patch-2/shoppinglist

I see the code, but I don't think you made an actual PR. I don't see any here.

**Comment by Aparna106** [comment]
I think I made one now.

**Comment by abhaikollara** [comment]
Merged in #8
